version: "3"

services:
  forms:
    image: sprout9/forms:latest
    container_name: forms
    depends_on:
      - mongodb
    restart: unless-stopped
    environment:
      MONGODB_URI: "${MONGODB_URI}"
      NODEMAILER_USER: "${NODEMAILER_USER}"
      NODEMAILER_PASS: "${NODEMAILER_PASS}"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
      NEXTAUTH_URL: "${NEXTAUTH_URL}"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - /data/mongodb/:/data/db

  nginx:
    image: sprout9/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - forms
    volumes:
      - /etc/letsencrypt:/etc/nginx/certs:ro
    restart: unless-stopped