- hosts: all
  become: yes
  tasks:
    - name: Get Linux device name for EBS volume
      ansible.builtin.shell:
        cmd: lsblk -o PATH,SERIAL | grep {{ ebs_volume_id | replace('-', '') }} | cut -d ' ' -f 1
      register: lsblk

    - name: Store EBS volume device name
      ansible.builtin.set_fact:
        ebs_volume_device_name: "{{ lsblk.stdout }}"

    - name: Mount EBS Volume
      mount:
        path: /data
        src: "{{ ebs_volume_device_name }}"
        fstype: ext4
        state: mounted
        boot: true
    
    # - name: Update all packages
    #   ansible.builtin.apt:
    #     update_cache: yes
    #     upgrade: yes

    # - name: Install Docker
    #   ansible.builtin.apt:
    #     name:
    #       - ca-certificates 
    #       - curl 
    #       - gnupg
    #     state: latest

    # - name: Add signing key
    #   ansible.builtin.apt_key:
    #     url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    #     state: present

    # - name: Add repository into sources list
    #   ansible.builtin.apt_repository:
    #     repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    #     state: present
    #     filename: docker

    # - name: Install Docker
    #   ansible.builtin.apt:
    #     name:
    #       - docker-ce 
    #       - docker-ce-cli 
    #       - containerd.io 
    #       - docker-buildx-plugin 
    #       - docker-compose-plugin
    #     state: latest
    #     update_cache: true

    # - name: Start Docker Service
    #   ansible.builtin.service:
    #     name: docker
    #     state: started
    #     enabled: yes

    # - name: Install Cron
    #   ansible.builtin.apt:
    #     name: cron
    #     state: latest

    # - name: Start Cron Service
    #   ansible.builtin.service:
    #     name: cron
    #     state: started
    #     enabled: yes

    # - name: Install Certbot
    #   ansible.builtin.apt:
    #     name: certbot
    #     state: latest

    # - name: Obtain a certificate from Let's Encrypt
    #   ansible.builtin.shell: |
    #     certbot certonly --standalone -d {{ domain_name }} -n --agree-tos -m {{ email_address }}
    #   args:
    #     creates: /etc/letsencrypt/live/{{ domain_name }}
    #   register: certbot_output
    #   changed_when: "'Congratulations' in certbot_output.stdout"
        



# /etc/letsencrypt/live/forms.sprout9.nl/fullchain.pem
# /etc/letsencrypt/live/forms.sprout9.nl/privkey.pem