name: Sprout9 Forms App Tags Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  push_forms_to_registry:
    name: Push Forms Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sprout9/forms
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./forms
          file: ./forms/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/arm64


  deploy_to_instance:
    name: Deploy latest forms app version to instance Docker
    runs-on: ubuntu-latest
    env:
      MONGO_INITDB_ROOT_USERNAME: "${{ secrets.MONGO_INITDB_ROOT_USERNAME }}"
      MONGO_INITDB_ROOT_PASSWORD: "${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}"
      MONGODB_URI: "mongodb://${{ secrets.MONGO_INITDB_ROOT_USERNAME }}:${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}@mongodb:27017/?authSource=admin"
      NODEMAILER_USER: "${{ vars.NODEMAILER_USER }}"
      NODEMAILER_PASS: "${{ secrets.NODEMAILER_PASS }}"
      NEXTAUTH_SECRET: "${{ secrets.NEXTAUTH_SECRET }}"
      NEXTAUTH_URL: "${{ vars.HTTPS_DOMAIN_NAME }}"
    needs:
      - push_forms_to_registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Download IP artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Setup SSH
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p /home/runner/.ssh/
          echo -e "${{ secrets.ED25519_PRIVATE_KEY }}" > /home/runner/.ssh/id_ed25519
          chmod 700 /home/runner/.ssh/id_ed25519
          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{ vars.DOMAIN_NAME }} >> /home/runner/.ssh/known_hosts

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Deploy
        run: |
          docker context create remote --docker "host=ssh://${{ secrets.REMOTE_USER }}@${{ vars.DOMAIN_NAME }}"
          docker context use remote
          docker-compose pull
          docker-compose up -d
