name: Sprout9 Forms App Tags Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  push_forms_to_registry:
    name: Push Forms Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sprout9/forms
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./forms
          file: ./forms/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/arm64,linux/amd64


  deploy_to_instance:
    name: Deploy latest forms app version to instance Docker
    runs-on: ubuntu-latest
    needs:
      - push_forms_to_registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Download IP artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Setup SSH
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p /home/runner/.ssh/
          echo -e "${{ secrets.ED25519_PRIVATE_KEY }}" > /home/runner/.ssh/id_ed25519
          chmod 700 /home/runner/.ssh/id_ed25519
          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{ vars.DOMAIN_NAME }} >> /home/runner/.ssh/known_hosts

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Deploy
        run: |
          docker context create remote --docker "host=ssh://${{ secrets.REMOTE_USER }}@${{ vars.DOMAIN_NAME }}"
          docker context use remote
          docker-compose pull forms
          export MONGO_INITDB_ROOT_USERNAME="${{ secrets.MONGO_INITDB_ROOT_USERNAME }}"
          export MONGO_INITDB_ROOT_PASSWORD="${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}"
          export MONGODB_URI="mongodb://${{ secrets.MONGO_INITDB_ROOT_USERNAME }}:${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}@mongodb:27017/?authSource=admin"
          export NODEMAILER_USER="${{ vars.NODEMAILER_USER }}"
          export NODEMAILER_PASS="${{ secrets.NODEMAILER_PASS }}"
          export NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}"
          export NEXTAUTH_URL="${{ vars.HTTPS_DOMAIN_NAME }}"
          docker-compose up -d forms
